In [1]:
from asyncio import gather

import numpy as np

precios = np.array([2.50, 3.00, 1.75, 2.20]) ## np.array() crea un array unidimensional
print(precios)
max_cafes = np.floor(10/precios)
print(max_cafes)
el_mayor = max_cafes.max()
posicion_del_mayor = max_cafes.argmax()
print("Mayor cantidad de cafés que se pueden comprar es: ", el_mayor, "Y se encuentra en la posición: ", posicion_del_mayor)


[2.5  3.   1.75 2.2 ]
[4. 3. 5. 4.]
Mayor cantidad de cafés que se pueden comprar es:  5.0 Y se encuentra en la posición:  2


In [16]:
import pandas as pd
# Para crear un diccionario con datos:
data = {
    'Nombre': ['Juan', 'Ana', 'Pedro', 'María'],
    'Edad': [23, 45,32,19],
    'Ciudad': ['Madrid', 'Barcelona', 'Valencia', 'Servilla']
}

# Crear un DataFrame a partir del diccionario
df = pd.DataFrame(data, columns=['Nombre', 'Edad', 'Ciudad'])
print(df['Nombre'])

print("ACCEDIENDO A LA PRIMERA FILA")
print(df.iloc[2])

print("FILTRANDO")
filtro = df[df['Edad']>30]
print(filtro)

df['Trabajo'] = ['Ingeniero', 'Médico', 'Abogado', 'Profesor']
print("SE AGREGÓ UN NUEVO CAMPO")
print(df)


##COMENTADOS: Para eliminar una columna hacemos: df = df.drop(columns = ['Trabajo'])
print(df)
print(df.drop(columns=['Trabajo']))


0     Juan
1      Ana
2    Pedro
3    María
Name: Nombre, dtype: object
ACCEDIENDO A LA PRIMERA FILA
Nombre       Pedro
Edad            32
Ciudad    Valencia
Name: 2, dtype: object
FILTRANDO
  Nombre  Edad     Ciudad
1    Ana    45  Barcelona
2  Pedro    32   Valencia
SE AGREGÓ UN NUEVO CAMPO
  Nombre  Edad     Ciudad    Trabajo
0   Juan    23     Madrid  Ingeniero
1    Ana    45  Barcelona     Médico
2  Pedro    32   Valencia    Abogado
3  María    19   Servilla   Profesor
  Nombre  Edad     Ciudad    Trabajo
0   Juan    23     Madrid  Ingeniero
1    Ana    45  Barcelona     Médico
2  Pedro    32   Valencia    Abogado
3  María    19   Servilla   Profesor
  Nombre  Edad     Ciudad
0   Juan    23     Madrid
1    Ana    45  Barcelona
2  Pedro    32   Valencia
3  María    19   Servilla
  Nombre  Edad     Ciudad    Trabajo
0   Juan    23     Madrid  Ingeniero
1    Ana    45  Barcelona     Médico
2  Pedro    32   Valencia    Abogado
3  María    19   Servilla   Profesor


In [28]:
##CONTROL DE HORAS DE LABORATORIO
import pandas as pd
datos = {
    'Estudiante': ['Ana', 'Luis', 'Mariía','Juan', 'Carla'],
    'Horas_usadas': [3, 5, 2, 4, 1]
}

df = pd.DataFrame(datos)
df['Costo_total'] = df['Horas_usadas'] * 2.0

print("AQUÍ EL DATAFRAME CON EL COSTO TOTAL POR ESTUDIANTE:")

print(df)
print("")

print("USANDO .head():")

print(df.head())

print("Calculo de estadísticas descriptivas:")
print(df['Costo_total'].describe())

filtro = df[df['Costo_total']>6.0]
print("Filas con costo total > 6: ")
print(filtro)

print("RESUMEN: ")
print("El gato promedio fue de S/. x.xx; los estudiantes que gastaron más de S/. 6.00 son : ")
print(filtro)

AQUÍ EL DATAFRAME CON EL COSTO TOTAL POR ESTUDIANTE:
  Estudiante  Horas_usadas  Costo_total
0        Ana             3          6.0
1       Luis             5         10.0
2     Mariía             2          4.0
3       Juan             4          8.0
4      Carla             1          2.0

USANDO .head():
  Estudiante  Horas_usadas  Costo_total
0        Ana             3          6.0
1       Luis             5         10.0
2     Mariía             2          4.0
3       Juan             4          8.0
4      Carla             1          2.0
Calculo de estadísticas descriptivas:
count     5.000000
mean      6.000000
std       3.162278
min       2.000000
25%       4.000000
50%       6.000000
75%       8.000000
max      10.000000
Name: Costo_total, dtype: float64
Filas con costo total > 6: 
  Estudiante  Horas_usadas  Costo_total
1       Luis             5         10.0
3       Juan             4          8.0
RESUMEN: 
El gato promedio fue de S/. x.xx; los estudiantes que gastaron más d

In [7]:
import numpy as np

distancia = np.array([12, 23, 31, 41, 9])
matriz = np.array([[1,2,3,4],
                   [5,6,7,8]])

def printDistancias():
    maximo = distancia.max()
    posicion = distancia.argmax()
    print("El mayor número ", maximo, " está en la posición: ", posicion)

printDistancias()
print(matriz)
print(distancia)

max_cafes = np.floor(10/distancia)
print(max_cafes)

El mayor número  41  está en la posición:  3
[[1 2 3 4]
 [5 6 7 8]]
[12 23 31 41  9]
[0. 0. 0. 0. 1.]


 ### 1. FOTOCOPIAS PARA APUNTES
<i> La primera práctica

In [14]:
import numpy as np

##1. Fotocopias para apuntes
presupuesto = 8.00
precios = np.array([0.10, 0.12, 0.08])
copisterias = np.array(["A", "B", "C"])

paginas = np.floor(presupuesto/precios)
total = precios.size

max_pages = paginas.max()
posicion_mayor = paginas.argmax()

for i in range(precios.size):
    print("En la copistería ", copisterias[i], " puede sacar ", paginas[i], " páginas")

print("En la copistería ", copisterias[posicion_mayor], " se puede comprar ", max_pages, " páginas")

En la copistería  A  puede sacar  80.0  páginas
En la copistería  B  puede sacar  66.0  páginas
En la copistería  C  puede sacar  100.0  páginas
En la copistería  C  se puede comprar  100.0  páginas


### 3. Préstamos de libros en la biblioteca
<i> Otra práctica más.

In [23]:
import pandas as pd
datos = {
    'estudiantes': ["Rosa", "David", "Elena", "Mario", "Paula"],
    'dias_prestamo': [7,10,5,12,3]
}
df = pd.DataFrame(datos, columns=['estudiantes', 'dias_prestamo'])


##print(df['dias_prestamo'].describe())


##Ahora para el filtro usamos:
df_mayores_8 = df[df['dias_prestamo']>8]
df_david = df[df['estudiantes'] == 'David']
print(df_david)
print(df_mayores_8)

print(df)




  estudiantes  dias_prestamo
1       David             10
  estudiantes  dias_prestamo
1       David             10
3       Mario             12
  estudiantes  dias_prestamo
0        Rosa              7
1       David             10
2       Elena              5
3       Mario             12
4       Paula              3


## 4. Gastos de almuerzo semanal

In [29]:
import pandas as pd

datos = {
    'dias': ["lunes", "martes", "miercoles", "jueves", "viernes"],
    'gastos': [4.0, 3.5, 5.0, 4.2, 3.8]
}

df = pd.DataFrame(datos, columns=['dias', 'gastos'])

gasto_total = df['gastos'].sum()
gasto_medio = df['gastos'].mean()

dias_mas_promedio = df[df['gastos'] > gasto_medio]

print("Gasto total: ", gasto_total)
print("Gasto medio: ", gasto_medio)
print("Días donde se gastaron más que el promedio: ", dias_mas_promedio['dias'].size)
for i in range(3):
    print(i)




Gasto total:  20.5
Gasto medio:  4.1
Días donde se gastaron más que el promedio:  2
0
1
2


In [11]:
import numpy as np

# Definimos la función objetivo
def funcion_objetivo(x):
    return -(x - 3)**2 + 10

# Algoritmo Hill Climbing
def hill_climbing():
    # Estado inicial
    x = 0  # Comenzamos en un valor arbitrario, por ejemplo 0
    paso = 0.1  # El tamaño del paso que damos
    iteraciones = 100  # Limite de iteraciones

    for _ in range(iteraciones):
        # Generamos dos vecinos (movimiento hacia la izquierda y la derecha)
        vecinos = [x - paso, x + paso]
        valores_vecinos = [funcion_objetivo(v) for v in vecinos]

        # Evaluamos qué vecino tiene el mejor valor de la función objetivo
        mejor_valor = max(valores_vecinos)
        if mejor_valor <= funcion_objetivo(x):
            # Si no encontramos un vecino mejor, terminamos
            print(f"Óptimo local encontrado en x = {x} con f(x) = {funcion_objetivo(x)}")
            break

        # Si encontramos un vecino mejor, nos movemos hacia él
        x = vecinos[valores_vecinos.index(mejor_valor)]

    return x

# Ejecutamos el algoritmo
resultado = hill_climbing()
print(f"Resultado final: x = {resultado}, f(x) = {funcion_objetivo(resultado)}")


Óptimo local encontrado en x = 3.0000000000000013 con f(x) = 10.0
Resultado final: x = 3.0000000000000013, f(x) = 10.0


In [12]:
import numpy as np

# Matriz de distancias entre facultades (en minutos)
# Ejemplo de matriz de costos entre las 6 facultades
# Los valores son representativos de los tiempos de viaje entre las facultades
costos = np.array([
    [0, 10, 15, 20, 25, 30],  # Distancias desde la facultad 0
    [10, 0, 35, 25, 30, 20],  # Distancias desde la facultad 1
    [15, 35, 0, 30, 25, 10],  # Distancias desde la facultad 2
    [20, 25, 30, 0, 15, 5],   # Distancias desde la facultad 3
    [25, 30, 25, 15, 0, 10],  # Distancias desde la facultad 4
    [30, 20, 10, 5, 10, 0]    # Distancias desde la facultad 5
])

# Función para calcular el tiempo total de una ruta
def calcular_tiempo(ruta):
    tiempo_total = 0
    for i in range(len(ruta) - 1):
        tiempo_total += costos[ruta[i], ruta[i + 1]]  # Sumar el tiempo entre facultades consecutivas
    tiempo_total += costos[ruta[-1], ruta[0]]  # Volver al punto de inicio (facultad 0)
    return tiempo_total

# Función Hill Climbing para optimizar la ruta
def hill_climbing():
    ruta_actual = [0, 1, 2, 3, 4, 5, 0]  # Ruta inicial (comienza en la facultad 0)
    tiempo_actual = calcular_tiempo(ruta_actual)

    while True:
        vecinos = []  # Lista para almacenar las rutas vecinas

        # Generar vecinos intercambiando dos facultades consecutivas
        for i in range(1, len(ruta_actual) - 2):  # Evitamos el primer y último elemento
            vecino = ruta_actual[:]
            vecino[i], vecino[i + 1] = vecino[i + 1], vecino[i]  # Intercambiar dos facultades
            vecinos.append(vecino)

        mejor_ruta = ruta_actual
        mejor_tiempo = tiempo_actual

        # Evaluar los vecinos y elegir el mejor
        for vecino in vecinos:
            tiempo_vecino = calcular_tiempo(vecino)
            if tiempo_vecino < mejor_tiempo:
                mejor_ruta = vecino
                mejor_tiempo = tiempo_vecino

        # Si no encontramos ninguna mejora, terminamos
        if mejor_ruta == ruta_actual:
            break

        # Si encontramos una mejor ruta, la actualizamos
        ruta_actual = mejor_ruta
        tiempo_actual = mejor_tiempo

        print(f"Ruta mejorada: {ruta_actual} con tiempo: {tiempo_actual} minutos")

    return ruta_actual, tiempo_actual

# Ejecutar el algoritmo
ruta_optima, tiempo_optimo = hill_climbing()
print(f"\nRuta final óptima: {ruta_optima} con tiempo total: {tiempo_optimo} minutos")


Ruta mejorada: [0, 1, 2, 3, 5, 4, 0] con tiempo: 115 minutos
Ruta mejorada: [0, 1, 2, 5, 3, 4, 0] con tiempo: 100 minutos

Ruta final óptima: [0, 1, 2, 5, 3, 4, 0] con tiempo total: 100 minutos


In [5]:
#Crear una lista
mi_lista = [10, 20, 25, 43, 5]
primer_elemento = mi_lista[0]
print(primer_elemento)

#Para modificar elemento:
mi_lista[0] = 20
print(mi_lista[0])
print(primer_elemento)

print(f"lista modificada: {mi_lista}")

#Para añadir un elemento al final
mi_lista.append(20)
print(f"mi lista con un elemento adicional: {mi_lista}")


10
20
10
lista modificada: [20, 20, 25, 43, 5]
mi lista con un elemento adicional: [20, 20, 25, 43, 5, 20]


In [5]:
##APLICANDO HILL CLIMBING
##Función objetivo:
def funcion_objetivo(x):
    return -(x - 3)**2 + 10

##Variables de decisión:
# x
def hill_climbing(funcion, inicio, paso = 0.1, max_iter=1000):
    actual = inicio
    actual_valor = funcion_objetivo(actual)

    for _ in range(max_iter):
        ##evaluar vecinos inmediatos: izquierda y derecha
        vecino_izq = actual - paso
        vecino_der = actual + paso

        ##Encontrar el mejor vecino
        valor_izq = funcion_objetivo(vecino_izq)
        valor_der = funcion_objetivo(vecino_der)

        ##Encontrando el mejor vecino
        mejor_vecino = actual
        mejor_valor = actual_valor

        if valor_izq > mejor_valor:
            mejor_vecino = vecino_izq
            mejor_valor = valor_izq
        if valor_der > mejor_valor:
            mejor_vecino = vecino_der
            mejor_valor = valor_der

        #Si no hay más mejoras, hemos llegado al pico local
        if mejor_valor <= actual_valor:
            break
        ##Actualizar al mejor vecino
        actual = mejor_vecino
        actual_valor = mejor_valor
    return actual, actual_valor

#USÁNDOLO
inicio = 0 #punto inicial
resultado, valor = hill_climbing(funcion_objetivo, inicio)
print(f"Máximo aproximado en x = {resultado:.4f} con valor = {valor:.4f}")



Máximo aproximado en x = 3.0000 con valor = 10.0000


In [67]:
import math
import random

def funcion_objetivo(x):
    return -(x - 3)**2 + 10

def recocido_simulado(funcion, inicio, temp_inicial=10, temp_min=0.01, alfa=0.9, paso=0.1, max_iter=1000):
    actual = inicio
    actual_valor = funcion(actual)
    temperatura = temp_inicial

    iteracion = 0
    while temperatura > temp_min and iteracion < max_iter:
        # Generar vecino aleatorio (izquierda o derecha)
        if random.random() < 0.5:
            vecino = actual + paso
        else:
            vecino = actual - paso

        vecino_valor = funcion(vecino)
        cambio_calidad = vecino_valor - actual_valor

        # Si mejora, aceptar
        if cambio_calidad > 0:
            actual = vecino
            actual_valor = vecino_valor
        else:
            # Si empeora, aceptar con probabilidad P
            probabilidad = math.exp(cambio_calidad / temperatura)
            if random.random() < probabilidad:
                actual = vecino
                actual_valor = vecino_valor

        # Reducir temperatura
        temperatura *= alfa
        iteracion += 1

    return actual, actual_valor

# Uso del algoritmo
inicio = 0
resultado, valor = recocido_simulado(funcion_objetivo, inicio)

print(f"Máximo aproximado en x = {resultado:.4f} con valor = {valor:.4f}")


Máximo aproximado en x = 2.5000 con valor = 9.7500


In [16]:
import math
value = math.exp(0.5)
print(value)


1.6487212707001282
